[[headers]]
  for = "/search.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://shortcomix.blogspot.com"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/pdfjs/web/viewer.html" 
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://shortcomix.blogspot.com"