[[headers]]
  for = "/search.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://shortcomix.blogspot.com"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/files/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://shortcomix.blogspot.com"
    Content-Security-Policy = "frame-ancestors https://shortcomix.blogspot.com"
    Content-Type = "application/pdf"
    Content-Disposition = "inline"
